---
# This GitHub Actions workflow is calculating code coverage of extension and creates a badge for it.
name: Code coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  code-coverage:
    name: "Calculate code coverage"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: xdebug
          extensions: xdebug, sqlite
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - env:
          TYPO3: "${{ matrix.typo3 }}"
        name: "Install TYPO3 Core"
        run: |
          composer require --no-progress typo3/minimal:"$TYPO3"
          composer show
      - name: "Run functional tests with coverage"
        run: composer ci:coverage:functional
      - name: "Run unit tests with coverage"
        run: composer ci:coverage:unit
      - name: "Merge coverage results"
        run: composer ci:coverage:merge
      - name: "Upload coverage results to Coveralls"
        if: ${{ matrix.php != '8.0'}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php }}
        run: .Build/vendor/bin/php-coveralls
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
        typo3:
          - ^11.5
  finish:
    needs: code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COREVALLS_TOKEN }}
          parallel-finished: true